const destinations = [
    { label: "Tel Aviv", value: "TLV" },
    { label: "New York", value: "JFK" },
    { label: "London", value: "LHR" },
    { label: "Paris", value: "PAR" },
    { label: "Tokyo", value: "HND" },
    { label: "Los Angeles", value: "LAX" },
    { label: "Chicago", value: "ORD" },
    { label: "Dubai", value: "DXB" },
    { label: "Singapore", value: "SIN" },
    { label: "Hong Kong", value: "HKG" },
    { label: "Toronto", value: "YYZ" },
    { label: "Sydney", value: "SYD" },
    { label: "Melbourne", value: "MEL" },
    { label: "San Francisco", value: "SFO" },
    { label: "Beijing", value: "PEK" },
    { label: "Shanghai", value: "PVG" },
    { label: "Munich", value: "MUC" },
    { label: "Frankfurt", value: "FRA" },
    { label: "Amsterdam", value: "AMS" },
    { label: "Seoul", value: "ICN" },
    { label: "Bangkok", value: "BKK" },
    { label: "Delhi", value: "DEL" },
    { label: "Mumbai", value: "BOM" },
    { label: "Barcelona", value: "BCN" },
    { label: "Rome", value: "FCO" },
    { label: "Madrid", value: "MAD" },
    { label: "Zurich", value: "ZRH" },
    { label: "Vienna", value: "VIE" },
    { label: "Istanbul", value: "IST" },
    { label: "Doha", value: "DOH" },
    { label: "Lisbon", value: "LIS" },
    { label: "Oslo", value: "OSL" },
    { label: "Stockholm", value: "ARN" },
    { label: "Copenhagen", value: "CPH" },
    { label: "Dublin", value: "DUB" },
    { label: "Brussels", value: "BRU" },
    { label: "Athens", value: "ATH" },
    { label: "Budapest", value: "BUD" },
    { label: "Warsaw", value: "WAW" },
    { label: "Prague", value: "PRG" },
    { label: "Helsinki", value: "HEL" },
    { label: "Vienna", value: "VIE" },
    { label: "Dubai", value: "DXB" },
    { label: "Riyadh", value: "RUH" },
    { label: "Jeddah", value: "JED" },
    { label: "Cairo", value: "CAI" },
    { label: "Johannesburg", value: "JNB" },
    { label: "Buenos Aires", value: "EZE" },
    { label: "Rio de Janeiro", value: "GIG" },
    { label: "Santiago", value: "SCL" },
    { label: "Lima", value: "LIM" },
    { label: "Bogotá", value: "BOG" },
    { label: "Mexico City", value: "MEX" },
    { label: "São Paulo", value: "GRU" },
    { label: "Caracas", value: "CCS" },
    { label: "Panama City", value: "PTY" },
    { label: "Havana", value: "HAV" },
    { label: "Kingston", value: "KIN" },
    { label: "Santo Domingo", value: "SDQ" },
    { label: "Nassau", value: "NAS" },
    { label: "Montego Bay", value: "MBJ" },
    { label: "San Juan", value: "SJU" },
    { label: "Punta Cana", value: "PUJ" },
    { label: "Guatemala City", value: "GUA" },
    { label: "San José", value: "SJO" },
    { label: "Managua", value: "MGA" },
    { label: "San Salvador", value: "SAL" },
    { label: "Tegucigalpa", value: "TGU" },
    { label: "Belize City", value: "BZE" },
    { label: "Ottawa", value: "YOW" },
    { label: "Montreal", value: "YUL" },
    { label: "Vancouver", value: "YVR" },
    { label: "Calgary", value: "YYC" },
    { label: "Edmonton", value: "YEG" },
    { label: "Halifax", value: "YHZ" },
    { label: "Winnipeg", value: "YWG" },
    { label: "Quebec City", value: "YQB" },
    { label: "Victoria", value: "YYJ" },
    { label: "St. Johns", value: "YYT" },
    { label: "Regina", value: "YQR" },
    { label: "Saskatoon", value: "YXE" },
    { label: "Las Vegas", value: "LAS" },
    { label: "Atlanta", value: "ATL" },
    { label: "Dallas", value: "DFW" },
    { label: "Miami", value: "MIA" },
    { label: "Boston", value: "BOS" },
    { label: "Houston", value: "IAH" },
    { label: "Orlando", value: "MCO" },
    { label: "Seattle", value: "SEA" },
    { label: "Denver", value: "DEN" },
    { label: "Philadelphia", value: "PHL" },
    { label: "Washington", value: "DCA" },
    { label: "San Diego", value: "SAN" },
    { label: "Tampa", value: "TPA" },
    { label: "Charlotte", value: "CLT" },
    { label: "Phoenix", value: "PHX" },
    { label: "Minneapolis", value: "MSP" },
    { label: "Detroit", value: "DTW" },
    { label: "Salt Lake City", value: "SLC" },
    { label: "Baltimore", value: "BWI" },
    { label: "St. Louis", value: "STL" },
    { label: "Portland", value: "PDX" },
    { label: "San Antonio", value: "SAT" },
    { label: "Dallas", value: "DAL" },
    { label: "Kansas City", value: "MCI" },
    { label: "Indianapolis", value: "IND" },
    { label: "Fort Lauderdale", value: "FLL" },
    { label: "Pittsburgh", value: "PIT" },
    { label: "New Orleans", value: "MSY" },
    { label: "Cleveland", value: "CLE" },
    { label: "Cincinnati", value: "CVG" },
    { label: "Honolulu", value: "HNL" },
    { label: "Milwaukee", value: "MKE" },
    { label: "Columbus", value: "CMH" },
    { label: "Raleigh", value: "RDU" },
    { label: "Hartford", value: "BDL" },
    { label: "Nashville", value: "BNA" },
    { label: "Austin", value: "AUS" },
    { label: "Louisville", value: "SDF" },
    { label: "Albuquerque", value: "ABQ" },
    { label: "El Paso", value: "ELP" },
    { label: "Tucson", value: "TUS" },
    { label: "Richmond", value: "RIC" },
    { label: "Buffalo", value: "BUF" },
    { label: "Omaha", value: "OMA" },
    { label: "Providence", value: "PVD" },
    { label: "Reno", value: "RNO" },
    { label: "Boise", value: "BOI" },
    { label: "Birmingham", value: "BHM" },
    { label: "Jacksonville", value: "JAX" },
    { label: "Des Moines", value: "DSM" },
    { label: "Oklahoma City", value: "OKC" },
    { label: "Charleston", value: "CHS" },
    { label: "Greensboro", value: "GSO" },
    { label: "Little Rock", value: "LIT" },
    { label: "Spokane", value: "GEG" },
    { label: "Knoxville", value: "TYS" },
    { label: "Springfield", value: "SGF" },
    { label: "Grand Rapids", value: "GRR" },
    { label: "Anchorage", value: "ANC" },
    { label: "Mobile", value: "MOB" },
    { label: "Wichita", value: "ICT" },
    { label: "Madison", value: "MSN" },
    { label: "Dayton", value: "DAY" },
    { label: "Burlington", value: "BTV" },
    { label: "Norfolk", value: "ORF" },
    { label: "Fresno", value: "FAT" },
    { label: "Pensacola", value: "PNS" },
    { label: "Lexington", value: "LEX" },
    { label: "Lubbock", value: "LBB" },
    { label: "Amarillo", value: "AMA" },
    { label: "Shreveport", value: "SHV" },
    { label: "Corpus Christi", value: "CRP" },
    { label: "Columbia", value: "CAE" },
    { label: "Augusta", value: "AGS" },
    { label: "Chattanooga", value: "CHA" },
    { label: "Roanoke", value: "ROA" },
    { label: "Santa Barbara", value: "SBA" },
    { label: "Harrisburg", value: "MDT" },
    { label: "Billings", value: "BIL" },
    { label: "Asheville", value: "AVL" },
    { label: "Fort Wayne", value: "FWA" },
    { label: "Lincoln", value: "LNK" },
    { label: "Appleton", value: "ATW" },
    { label: "Yakima", value: "YKM" },
    { label: "Santa Ana", value: "SNA" },
    { label: "Redding", value: "RDD" },
    { label: "Santa Rosa", value: "STS" },
    { label: "Monterey", value: "MRY" },
    { label: "Stockton", value: "SCK" },
    { label: "Riverside", value: "RIV" },
    { label: "Victorville", value: "VCV" },
    { label: "Oxnard", value: "OXR" },
    { label: "Palmdale", value: "PMD" },
    { label: "Hagerstown", value: "HGR" },
    { label: "Frederick", value: "FDK" },
    { label: "Easton", value: "ESN" },
    { label: "Cumberland", value: "CBE" },
    { label: "Ocean City", value: "OCE" },
    { label: "College Park", value: "CGS" },
    { label: "Paris", value: "CDG" },
    { label: "New York", value: "NYC" },
    { label: "London", value: "LON" },
    { label: "Tokyo", value: "TYO" },
    { label: "Sydney", value: "SYD" },
    { label: "Rome", value: "ROM" },
    { label: "Barcelona", value: "BCN" },
    { label: "Amsterdam", value: "AMS" },
    { label: "Berlin", value: "BER" },
    { label: "Dubai", value: "DXB" },
    { label: "Hong Kong", value: "HKG" },
    { label: "Bangkok", value: "BKK" },
    { label: "Istanbul", value: "IST" },
    { label: "Vienna", value: "VIE" },
    { label: "Madrid", value: "MAD" },
    { label: "Lisbon", value: "LIS" },
    { label: "Venice", value: "VCE" },
    { label: "Florence", value: "FLR" },
    { label: "Milan", value: "MIL" },
    { label: "Prague", value: "PRG" },
    { label: "Budapest", value: "BUD" },
    { label: "Moscow", value: "MOW" },
    { label: "Saint Petersburg", value: "LED" },
    { label: "Warsaw", value: "WAW" },
    { label: "Stockholm", value: "STO" },
    { label: "Copenhagen", value: "CPH" },
    { label: "Helsinki", value: "HEL" },
    { label: "Oslo", value: "OSL" },
    { label: "Reykjavik", value: "REK" },
    { label: "Athens", value: "ATH" },
    { label: "Zurich", value: "ZRH" },
    { label: "Geneva", value: "GVA" },
    { label: "Brussels", value: "BRU" },
    { label: "Dublin", value: "DUB" },
    { label: "Edinburgh", value: "EDI" },
    { label: "Glasgow", value: "GLA" },
    { label: "Manchester", value: "MAN" },
    { label: "Liverpool", value: "LPL" },
    { label: "Birmingham", value: "BHX" },
    { label: "Leeds", value: "LBA" },
    { label: "Bristol", value: "BRS" },
    { label: "Cardiff", value: "CWL" },
    { label: "Belfast", value: "BFS" },
    { label: "Lisbon", value: "LIS" },
    { label: "Porto", value: "OPO" },
    { label: "Marseille", value: "MRS" },
    { label: "Lyon", value: "LYS" },
    { label: "Toulouse", value: "TLS" },
    { label: "Nice", value: "NCE" },
    { label: "Nantes", value: "NTE" },
    { label: "Strasbourg", value: "SXB" },
    { label: "Bordeaux", value: "BOD" },
    { label: "Montpellier", value: "MPL" },
    { label: "Lille", value: "LIL" },
    { label: "Rennes", value: "RNS" },
    { label: "Grenoble", value: "GNB" },
    { label: "Dijon", value: "DIJ" },
    { label: "Avignon", value: "AVN" },
    { label: "Limoges", value: "LIG" },
    { label: "Clermont-Ferrand", value: "CFE" },
    { label: "Amiens", value: "QAM" },
    { label: "Rouen", value: "URO" },
    { label: "Le Havre", value: "LEH" },
    { label: "Reims", value: "RHE" },
    { label: "Tours", value: "TUF" },
    { label: "Orleans", value: "ORE" },
    { label: "Metz", value: "ETZ" },
    { label: "Mulhouse", value: "MLH" },
    { label: "Besancon", value: "QBQ" },
    { label: "Angers", value: "ANE" },
    { label: "Boulogne-Billancourt", value: "BOU" },
    { label: "Argenteuil", value: "ARG" },
    { label: "Saint-Denis", value: "SDN" },
    { label: "Roubaix", value: "ROU" },
    { label: "Tourcoing", value: "TOU" },
    { label: "Nanterre", value: "NAN" },
    { label: "Creteil", value: "CRL" },
    { label: "Saint-Denis", value: "SDN" },
    { label: "Poitiers", value: "PIS" },
    { label: "Perpignan", value: "PGF" },
    { label: "Mulhouse", value: "MLH" },
    { label: "Caen", value: "CFR" },
    { label: "Annecy", value: "NCY" },
    { label: "Beziers", value: "BZR" },
    { label: "Pau", value: "PUF" },
    { label: "Saint-Nazaire", value: "SNR" },
    { label: "Mans", value: "LME" },
    { label: "Valenciennes", value: "VA" },
    { label: "Cholet", value: "CET" },
    { label: "Lorient", value: "LRT" },
    { label: "Chambery", value: "CMF" },
    { label: "Niort", value: "NIT" },
    { label: "Troyes", value: "QYR" },
    { label: "Saint-Quentin", value: "SQT" },
    { label: "Cherbourg", value: "CER" },
    { label: "Arras", value: "QRV" },
    { label: "Laval", value: "LVA" },
    { label: "Blois", value: "XBQ" },
    { label: "Bayeux", value: "BYU" },
    { label: "Colmar", value: "CMR" },
    { label: "Albi", value: "LBI" },
    { label: "Saint-Malo", value: "SA" },
    { label: "Bastia", value: "BIA" },
    { label: "Ajaccio", value: "AJA" },
    { label: "Tarbes", value: "LDE" },
    { label: "Angouleme", value: "ANG" },
    { label: "Nevers", value: "NVS" },
    { label: "Rodez", value: "RDZ" },
    { label: "La Rochelle", value: "LRH" },
    { label: "Bourges", value: "BOU" },
    { label: "Montauban", value: "XMW" },
    { label: "Pontoise", value: "POX" },
    { label: "Meaux", value: "MEA" },
    { label: "Melun", value: "MEU" },
    { label: "Versailles", value: "XVE" },
    { label: "Nimes", value: "FNI" },
    { label: "Arles", value: "ZAF" },
    { label: "Frejus", value: "FRJ" },
    { label: "Saint-Raphael", value: "SRA" },
    { label: "Cannes", value: "CEQ" },
    { label: "Antibes", value: "ANT" },
    { label: "Grasse", value: "GSA" },
    { label: "Ajaccio", value: "AJA" },
    { label: "Bastia", value: "BIA" },
    { label: "Corte", value: "CZ" },
    { label: "Saint-Tropez", value: "STZ" },
    { label: "Sanary-sur-Mer", value: "SSM" },
    { label: "La Seyne-sur-Mer", value: "LSM" },
    { label: "Toulon", value: "TLN" },
    { label: "Hyères", value: "HYR" },
    { label: "Draguignan", value: "DRA" },
    { label: "Saint-Raphael", value: "SRH" },
    { label: "Avignon", value: "AVN" },
    { label: "Orange", value: "ORA" },
    { label: "Carpentras", value: "CPN" },
    { label: "Arles", value: "ARL" },
    { label: "Martigues", value: "MTG" },
    { label: "Salon-de-Provence", value: "SLP" },
    { label: "Aix-en-Provence", value: "AIX" },
    { label: "Marseille", value: "MRS" },
    { label: "Gap", value: "GAP" },
    { label: "Briancon", value: "BRC" },
    { label: "Digne-les-Bains", value: "DGB" },
    { label: "Forcalquier", value: "FCR" },
    { label: "Sisteron", value: "SIS" },
    { label: "Manosque", value: "MNS" },
    { label: "Nice", value: "NCE" },
    { label: "Grasse", value: "GRA" },
    { label: "Cannes", value: "CEQ" },
    { label: "Antibes", value: "ANB" },
    { label: "Vence", value: "VEN" },
    { label: "Beaulieu-sur-Mer", value: "BLS" },
    { label: "Mentone", value: "MEN" },
    { label: "Monaco", value: "MCM" },
    { label: "Sanremo", value: "SMO" },
    { label: "Genoa", value: "GOA" },
    { label: "Florence", value: "FLR" },
    { label: "Venice", value: "VCE" },
    { label: "Naples", value: "NAP" },
    { label: "Pisa", value: "PSA" },
    { label: "Siena", value: "SIE" },
    { label: "Bologna", value: "BLQ" },
    { label: "Turin", value: "TRN" },
    { label: "Milan", value: "MXP" },
    { label: "Rome", value: "FCO" },
    { label: "Palermo", value: "PMO" },
    { label: "Catania", value: "CTA" },
    { label: "Messina", value: "MSN" },
    { label: "Syracuse", value: "SYR" },
    { label: "Rimini", value: "RMI" },
    { label: "Verona", value: "VRN" },
    { label: "Padua", value: "PDA" },
    { label: "Trieste", value: "TRS" },
    { label: "Parma", value: "PMF" },
    { label: "Modena", value: "MOD" },
    { label: "Reggio Emilia", value: "RGM" },
    { label: "Ravenna", value: "RAV" },
    { label: "Ferrara", value: "FRR" },
    { label: "Cesena", value: "CES" },
    { label: "Forli", value: "FRL" },
    { label: "Perugia", value: "PEG" },
    { label: "Assisi", value: "ASS" },
    { label: "Gubbio", value: "GUB" },
    { label: "Spoleto", value: "SPT" },
    { label: "Orvieto", value: "ORV" },
    { label: "Terni", value: "TER" },
    { label: "Viterbo", value: "VTB" },
    { label: "Frosinone", value: "FRO" },
    { label: "Latina", value: "LTN" },
    { label: "Rieti", value: "RIE" },
    { label: "Teramo", value: "TE" },
    { label: "Pescara", value: "PSR" },
    { label: "L-Aquila", value: "LAQ" },
    { label: "Chieti", value: "CHI" },
    { label: "Campobasso", value: "CAM" },
    { label: "Isernia", value: "ISE" },
    { label: "Benevento", value: "BN" },
    { label: "Avellino", value: "AV" },
    { label: "Caserta", value: "CS" },
    { label: "Salerno", value: "SAL" },
    { label: "Pontedera", value: "PTE" },
    { label: "Viareggio", value: "VIA" },
    { label: "Lucca", value: "LC" },
    { label: "Massa", value: "MAS" },
    { label: "Livorno", value: "LIV" },
    { label: "Grosseto", value: "GR" },
    { label: "Siena", value: "SIE" },
    { label: "Arezzo", value: "ARZ" },
    { label: "Prato", value: "PTO" },
    { label: "Florence", value: "FLR" },
    { label: "Pistoia", value: "PT" },
    { label: "Modena", value: "MOD" },
    { label: "Ferrara", value: "FRR" },
    { label: "Ravenna", value: "RAV" },
    { label: "Bologna", value: "BLQ" },
    { label: "Rimini", value: "RMI" },
    { label: "Parma", value: "PMF" },
    { label: "Piacenza", value: "PC" },
    { label: "Reggio Emilia", value: "RGM" },
    { label: "Carpi", value: "CRP" },
    { label: "Forli", value: "FRL" },
    { label: "Cesena", value: "CES" },
    { label: "Imola", value: "IML" },
    { label: "Faenza", value: "FAE" },
    { label: "Rovigo", value: "ROV" },
    { label: "Vicenza", value: "VIC" },
    { label: "Treviso", value: "TSF" },
    { label: "Padua", value: "PDA" },
    { label: "Verona", value: "VRN" },
    { label: "Venice", value: "VCE" },
    { label: "Trieste", value: "TRS" },
    { label: "Gorizia", value: "GO" },
    { label: "Udine", value: "UD" },
    { label: "Bolzano", value: "BZO" },
    { label: "Trento", value: "TRN" },
    { label: "Belluno", value: "BL" },
    { label: "Aosta", value: "AOT" },
    { label: "Genoa", value: "GOA" },
    { label: "Savona", value: "SAV" },
    { label: "Imperia", value: "IMP" },
    { label: "La Spezia", value: "LAS" },
    { label: "Alessandria", value: "ALS" },
    { label: "Asti", value: "AST" },
    { label: "Biella", value: "BIE" },
    { label: "Cuneo", value: "CUF" },
    { label: "Novara", value: "NOV" },
    { label: "Turin", value: "TRN" },
    { label: "Vercelli", value: "VER" },
    { label: "Verbania", value: "VB" },
    { label: "Como", value: "COM" },
    { label: "Varese", value: "VAS" },
    { label: "Lecco", value: "LCO" },
    { label: "Sondrio", value: "SOD" },
    { label: "Monza", value: "MOZ" },
    { label: "Bergamo", value: "BGY" },
    { label: "Brescia", value: "BSC" },
    { label: "Cremona", value: "CRE" },
    { label: "Lodi", value: "LOD" },
    { label: "Mantua", value: "MNT" },
    { label: "Milan", value: "MXP" },
    { label: "Pavia", value: "PAV" }
]
export default destinations;
